language: python
python:
    - "2.6"

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
    - pip install flake8
    - pip install coverage

# command to run tests, e.g. python setup.py test
script:
    - make test
    # - make lint
    # - make flake8
